import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@componets/navbar";



export const metadata: Metadata = {
  title: "Fashion WoW",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="overflow-hidden">
        <Navbar />
        <main className="mx-auto border-r border-l overflow-y-auto h-screen border-gray-300 max-w-[900px] hide-scrollbar">
           {children}
        </main>
      </body>
    </html>
  );
}
